[options]
addons_path = D:\odoo18e\odoo\addons,D:\odoo18e\odoo\myaddons
admin_passwd = $pbkdf2-sha512$600000$SslZK8VY611rTel9T0lpTQ$MyB7PU4/qCwCtFiaa7l8LZ5J6NoG2QlqUsYYAEUPRDt/XpsJlmFm6jz5FMUyD3sHwxVN0aOpnzMLeK0Mx.P30g
db_name = odoo18e
db_filter = odoo18e
db_host = 127.0.0.1
db_port = 5432
db_user = odoo18e
db_password = odoo18e
http_port = 8069

